# This tools is powered by python
# but only 3.x
language: python

# Distributions targets python version
# Ensure this tool could be installed on major linux distros
python:
  - 3.4 # el7
  - 3.5 # debian / ubuntu
  - 3.6 # fedora
  - nightly

# Use pip cache to speed-up the build
cache: pip

# No problem if test failed on nightly python releases
matrix:
  allow_failures:
    - python: nightly

# Install python librairies
install:
  - pip install opster==4.1
  - pip install python-terraform==0.9.1
  - pip install pystache==0.5.4
  - pip install paramiko==2.4.0
  - pip install git+https://github.com/bkircher/python-rpm-spec.git#egg=python-rpm-spec
  - pip install pyflakes
  - pip install codecov

# Use standard python test process
script: python -m unittest

# If test suite is successful, update coverage
after_success:
  - codecov
  - pycodestyle .
  - pyflakes .

# Disable email notification
notifications:
  email: false
