language: python

python:
  - 3.4 # el7
  - 3.5 # debian / ubuntu
  - 3.6 # fedora
  - nightly

matrix:
  allow_failures:
    - python: nightly

install:
  - pip install -r requirements.txt
  - pip install pyflakes

script: python -m unittest

after_success:
  - coveralls
  - pip install pycodestyle pyflakes
  - pycodestyle .
  - pyflakes .
